name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linux Audio Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libgles2-mesa-dev xvfb

      - name: Install Tools and Dependencies
        run: |
          pip install --upgrade pip
          pip install "flet[cli]" flet-audio

      - name: Build Android Package
        run: |
          xvfb-run flet build apk --project-name angrybubu "Angry Bubu"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AngryBubu-APK
          path: build/apk/app-release.apk
